<a href="https://colab.research.google.com/github/RojaCM/Sample-files/blob/main/basicfunctions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PRINTING THE PATTERNS


In [ ]:
for i in range(4):
  for j in range(4):
    print('#',end= ' ')

  print()   


# # # # 
# # # # 
# # # # 
# # # # 


In [ ]:
for i in range(4):
  for j in range(i+1):
    print('#',end=' ')

  print() 

# 
# # 
# # # 
# # # # 


In [ ]:
for i in range(4):
  for j in range(4-i):
    print('#',end=' ')
    
  print()

# # # # 
# # # 
# # 
# 


In [ ]:
import numpy as np


In [ ]:
import array 
arr = np.array([1,2,3,4.0])

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
arr

array([1., 2., 3., 4.])

In [ ]:
a=np.linspace(0,15,7)

In [ ]:
a

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. ])

In [ ]:
  b = np.arange(1,20,2)

In [ ]:
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
c=np.logspace(1,5,6)

In [ ]:
c

array([1.00000000e+01, 6.30957344e+01, 3.98107171e+02, 2.51188643e+03,
       1.58489319e+04, 1.00000000e+05])

In [ ]:
num=8
for i in range(2,num):
  if num % i ==0:
    print('not a prime')
    break
else:
  print('prime number')


not a prime


In [ ]:
def fib(n):
  a=0
  b=1
  print(a)
  print(b)
  for i in range(2,n):
    
    c = a+b
    a=b
    b=c
    print(c)


In [ ]:
fib(10)

0
1
1
2
3
5
8
13
21
34


FACTORIAL NUMBER PROGRAM

In [ ]:
def fact(n):
  f = 1
  for i in range(1,n+1):
    f = f *i
  return f

In [ ]:
r= fact(5)

In [ ]:
r

120

Recursion function ---> the fucntion calling itself 
Factorial using recursion method

In [ ]:
def fact(n):
  if n==1:
    return 1
  else:
    return n * fact(n-1)

In [ ]:
f=fact(5)

In [ ]:
f

120

In [ ]:
f = lambda a,b: a+b
r=f(2,3)

In [ ]:
r

5

In [ ]:
nums=[2,5,7,6,8,12,13,15,14,16]
evens=list(filter(lambda i : i%2 ==0,nums))

In [ ]:
evens

[2, 6, 8, 12, 14, 16]

In [ ]:
update = list(map(lambda i:i*2,evens))

In [ ]:
update

[4, 12, 16, 24, 28, 32]

In [ ]:
from functools import reduce
red = reduce(lambda a,b:a+b,update)

In [ ]:
red

116

In [4]:
n= ['sun','mon','tue','wed','thu','fri']
l=[]
for i in n:
  print(i)
  l.append(i)


sun
mon
tue
wed
thu
fri
